// sveltekit/sveltekit-js/src/routes/page/[...slug]/+page.svelte
<script>
	/** @type {import('./$types').PageData} */
	export let data;
	const page = data.page;
</script>

<main>
    <div class="m-12">
      <h1 class="mb-4 text-5xl font-bold">{page.title}</h1>
      <p class="mb-8 text-lg">{page.body.text}</p>
  
      <p>
        <a href="/" class="underline">Back to homepage</a>
      </p>
    </div>
</main>

// nuxtjs/pages/page/[slug].vue
<script setup lang="ts">
const route = useRoute();
const { page } = await GqlPage({ slug: route.params.slug });
</script>

<template>
  <div class="m-12">
    <h1 class="text-5xl font-bold mb-4">{{ page.title }}</h1>
    <p class="text-lg mb-8">{{ page.body.text }}</p>

    <p>
      <nuxt-link to="/" class="underline">Back to homepage</nuxt-link>
    </p>
  </div>
</template>
